CREATE TABLE TEST.MYSERVERALL
(
  MESSAGE_NUM   VARCHAR2(12 CHAR),
  USER_ID       VARCHAR2(15 CHAR),
  MESSAGE       VARCHAR2(256 CHAR),
  MESSAGE_TYPE  CHAR(1 BYTE),
  LCHG_USER_ID  VARCHAR2(15 CHAR),
  LCHG_TIME     DATE,
  RCRE_USER_ID  VARCHAR2(15 CHAR),
  RCRE_TIME     DATE,
  TS_CNT        NUMBER(5)
)
TABLESPACE CENTRAL
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;



CREATE UNIQUE INDEX TEST.IDX_MYSERVERALL ON TEST.MYSERVERALL
(MESSAGE_NUM)
LOGGING
TABLESPACE TABLESPACEALL
PCTFREE    10
INITRANS   50
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX TEST.IDX_AMS_UMM01 ON TEST.MYSERVERALL
(USER_ID, MESSAGE_NUM, MESSAGE)
LOGGING
TABLESPACE TABLESPACEALL
PCTFREE    10
INITRANS   50
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX TEST.IDX_AMS_UMM04 ON TEST.MYSERVERALL
(MESSAGE, USER_ID, LCHG_TIME)
  TABLESPACE TABLESPACEALL
  PCTFREE    0
  INITRANS   100
  MAXTRANS   255
  STORAGE    (
              INITIAL          100M
              NEXT             100M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              FREELISTS        64
              BUFFER_POOL      DEFAULT
             )
LOGGING
GLOBAL PARTITION BY HASH (MESSAGE) (  
  PARTITION IDXG5_AMS_PART1
    TABLESPACE TABLESPACEALL,  
  PARTITION IDXG5_AMS_PART2
    TABLESPACE TABLESPACEALL,  
  PARTITION IDXG5_AMS_PART3
    TABLESPACE TABLESPACEALL,  
  PARTITION IDXG5_AMS_PART4
    TABLESPACE TABLESPACEALL,  
  PARTITION IDXG5_AMS_PART5
    TABLESPACE TABLESPACEALL,  
  PARTITION IDXG5_AMS_PART6
    TABLESPACE TABLESPACEALL,  
  PARTITION IDXG5_AMS_PART7
    TABLESPACE TABLESPACEALL,  
  PARTITION IDXG5_AMS_PART8
    TABLESPACE TABLESPACEALL
);
